### ISSUE TITLE
Load Int8 RN50 into deepmark, automate performance testing

### ISSUE THREAD

**Issue by mbrookhart** [NervanaSystems/ngraph-mxnet#301]
Acceptance Criteria:

1. Int8 RN50 model loaded into deepmark and/or quantization test added to deepmark and tested with RN50
2. RN50 Functional with nGraph + Quantization Fallback
3. Tickets Created for missing Quantized Ops

**Comment by ashokei** [comment]
https://github.com/NervanaSystems/mxnet-deepmark/pull/25
