### ISSUE TITLE
Make the Cmake build system work with nGraph

### ISSUE THREAD

**Issue by mbrookhart** [NervanaSystems/ngraph-mxnet#307]
Acceptance Criteria:

1) ngraph-mxnet can be built with gnu make or cmake
2) Both builds pass unit tests
3) Builds show the same performance in deepmark.

**Comment by cconvey** [comment]
@mbrookhart : We have some freedom regarding how we represent mxnet's dependency on ngraph:
1. git submodule
2. traditional external library
3. CMake ExternalProject

Do you know if the upstream maintainers have expressed a preference w.r.t. ngraph in particular?

**Comment by mbrookhart** [comment]
I think they want a submodule in the 3rdparty folder

**Comment by mbrookhart** [comment]
closed by #371
