### ISSUE TITLE
Make nGraph an MXNet submodule

### ISSUE THREAD

**Issue by mbrookhart** [NervanaSystems/ngraph-mxnet#308]
Acceptance Criteria:

1) ngraph registered as submodule
2) make (and cmake if https://github.com/NervanaSystems/ngraph-mxnet/issues/307 is done) automatically build the version of nGraph in the submodule
3) If the user supplies the compilation variable NGRAPH_DIR, a custom nGraph can be inserted instead of the submodule

**Comment by cconvey** [comment]
Things to deal with regarding Python packaging:
- [ ] Cython packaging works.  See [this example](https://github.com/apache/incubator-mxnet/issues/10738).
- [ ] `pip install -e .` makes ngraph-supplied .so files available as well.
- [ ] Python unit tests work correctly.
- [ ] nGraph-supplied files are provided as shared objects _or_ symlinks, as appropriate.  (Q: Can we back off this?  I.e., will `libmxnet.so` be the only consumer of these .so files when we use packaging?)

**Comment by mbrookhart** [comment]
I think we can belive libmxnet.so will be the only user. Bob's static PR may or may not simplify this.

**Comment by mbrookhart** [comment]
closed by #410
