### ISSUE TITLE
Automatically Test Inference Accuracy through Deepmark

### ISSUE THREAD

**Issue by mbrookhart** [NervanaSystems/ngraph-mxnet#323]
Ashok has added an inference accuracy function to deepmark based on random Data, we need to add pass/fail tests based on accuracy.

Acceptance Criteria:
1) Daily CI validating the accuracy of all tested deepmark models

**Comment by lnguyen-nvn** [comment]
https://github.com/NervanaSystems/ngraph-mxnet/pull/351
