### ISSUE TITLE
Verify MaskRCNN accuracy

### ISSUE THREAD

**Issue by louisfeng** [NervanaSystems/ngraph-mxnet#465]
Check inference results vs. baseline.

**Comment by louisfeng** [comment]
There was a bug in ngraph that's causing incorrect results. After some exhaustive debugging, I have found the sigmoid was not handling mkldnn input layout correctly. I'll make a PR to fix it. With that fixed, I think we have reasonable accuracy compared to the CPU baseline. I'll follow up with @lnguyen-nvn on testing.

**Comment by lnguyen-nvn** [comment]
Verify
