### ISSUE TITLE
Failed to check accuracy ssd-vgg16. Should use other model for testing SSD

### ISSUE THREAD

**Issue by lnguyen-nvn** [NervanaSystems/ngraph-mxnet#492]
https://aipg-rancher.intel.com/jenkins/algo-lr/job/ngraph-mxnet-run-accuracy-inference-models/153/console reported:
00:04:09.860366 nGraph: network:ssd-vgg16, type:inference, batch_size:1, accuracy:fail

I have coco data in /dataset/coco/

**Comment by lnguyen-nvn** [comment]
This is not urgent. However, I would like to sort it out this week.
Should I use ssd_300_vgg16_atrous_voc instead of ssd-vgg16 ?

**Comment by mbrookhart** [comment]
Yes, ssd-vgg16 by itself doesn't have a pretrained version, so real data inference testing is out the question. ssd_300_vgg16_atrous_voc is a close replacement we can test with real data.

**Comment by lnguyen-nvn** [comment]
Done
